---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-8 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-9 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.4.2
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04 CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test_with_coveralls
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=rubocop
  - rvm: 2.4.2
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "MARQfvJecdPQz1JCbXHasx7SmB2lxD7MqDLzSQ48Ky8wleh01brkvuN+v3OCtBTvuyGDK+QYvQD6ZH7+5Vs6LwlyMTeQm0qP8THskMJtlHKILpc+MvRKleNBoXnAlWjG/Owul1S10Tq7x7LfeQfAaG3k+l7qz+JMh/C7dAylwLv/hCjFr7WJ7pohKfA6+8tZxGRhcJDImKdQcp7N/iTaKopD3mXq9Swsy/WePa36jFIU9IsCHGmwJSxiQ+g79ybY5o81Or2MC4Xc4G7de5bWdFZg6r2aFqGXICetHYimVCHvEhmpGT6JfFMb+E/7hVAHHIBgwzHEKr6NHhZhJaebvjDx9BPtH+FsbRq1G0mMHRd72iHPptjXL36bMpmf+CmJJ2gjyMEgigqE/73+iqsfePjoj0yQdERRaZLE4rVDO7M/LHU1z8PP4OUVzDp1RuwTAPUO1IjpP/+gMxpSRrbAyWwkeWe+Cey3Z6YsEOmt6kyXVW8OdPTyg6C1Zk3YSOLZ5TpF7Uhad4Gyz8BGfz/ovxDuNC1hcenOJgANMRfglE8eFvYjjFo8mYD4KxydvvMTTt1V3j5nWlRrWQM8l9ZgOe7vtXFX4qGR35XDW6wyyDAWFzF3GkrZdbn/WBTaOiL+TsOFWJqqCT9W4rENVhGWhMGSvMVriMevrClvIoIHIPI="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
